<?php
if (PHP_SAPI !== 'cli') { http_response_code(404); exit; }
// CLI: php tools/generate_rings_logo.php — writes assets/images/hastra-rings-logo.svg: ten engraved gunmetal rings
// linked in a circle around an open palm and a four-point core star.
$C = 256; $F = 150; $n = 10; $r = 70.5; $band = 12;
$f = fn($v) => rtrim(rtrim(number_format($v, 2, '.', ''), '0'), '.');
$centers = [];
for ($i = 0; $i < $n; $i++) { $a = -M_PI / 2 + $i / $n * 2 * M_PI; $centers[] = [$C + cos($a) * $F, $C + sin($a) * $F]; }

// crossing points of ring i with ring i+1: outer one = i over, inner one = i+1 over
$clips = ''; $weave = '';
for ($i = 0; $i < $n; $i++) {
    [$ax, $ay] = $centers[$i]; [$bx, $by] = $centers[($i + 1) % $n];
    $d = hypot($bx - $ax, $by - $ay); $mx = ($ax + $bx) / 2; $my = ($ay + $by) / 2;
    $h = sqrt($r * $r - $d * $d / 4); $ux = -($by - $ay) / $d; $uy = ($bx - $ax) / $d;
    $out = (($mx - $C) * $ux + ($my - $C) * $uy) > 0 ? 1 : -1;
    $P = [$mx + $ux * $h * $out, $my + $uy * $h * $out]; $Q = [$mx - $ux * $h * $out, $my - $uy * $h * $out];
    $clips .= "    <clipPath id=\"xo$i\"><circle cx=\"{$f($P[0])}\" cy=\"{$f($P[1])}\" r=\"19\"/></clipPath>\n";
    $clips .= "    <clipPath id=\"xi$i\"><circle cx=\"{$f($Q[0])}\" cy=\"{$f($Q[1])}\" r=\"19\"/></clipPath>\n";
    $j = ($i + 1) % $n;
    $weave .= "      <use href=\"#rg$i\" clip-path=\"url(#xo$i)\"/><use href=\"#rg$j\" clip-path=\"url(#xi$i)\"/>\n";
}

$rings = ''; $uses = ''; $glints = '';
foreach ($centers as $i => [$x, $y]) {
    $cx = $f($x); $cy = $f($y);
    // one ring = dark outline, metal band, rim light, inner groove, engraving, specks
    $rings .= "    <g id=\"rg$i\">"
        . "<circle cx=\"$cx\" cy=\"$cy\" r=\"$r\" fill=\"none\" stroke=\"#050608\" stroke-width=\"" . ($band + 3) . "\"/>"
        . "<circle cx=\"$cx\" cy=\"$cy\" r=\"$r\" fill=\"none\" stroke=\"url(#metal)\" stroke-width=\"$band\"/>"
        . "<circle cx=\"$cx\" cy=\"$cy\" r=\"" . $f($r + 4.3) . "\" fill=\"none\" stroke=\"#e9eef5\" stroke-opacity=\".34\" stroke-width=\"1.2\"/>"
        . "<circle cx=\"$cx\" cy=\"$cy\" r=\"" . $f($r - 4.3) . "\" fill=\"none\" stroke=\"#000\" stroke-opacity=\".5\" stroke-width=\"1.2\"/>"
        . "<circle cx=\"$cx\" cy=\"$cy\" r=\"$r\" fill=\"none\" stroke=\"#07090d\" stroke-opacity=\".78\" stroke-width=\"3.6\" stroke-dasharray=\"2.2 1.4 0.8 2.6 3.1 1.2 1.1 3.4 2.4 1.6 0.7 2.2\" stroke-dashoffset=\"" . ($i * 7) . "\"/>"
        . "<circle cx=\"$cx\" cy=\"$cy\" r=\"" . $f($r + 1.8) . "\" fill=\"none\" stroke=\"#dfe7f0\" stroke-opacity=\".55\" stroke-width=\"1.3\" stroke-linecap=\"round\" stroke-dasharray=\"0.1 9 0.1 14 0.1 6\" stroke-dashoffset=\"" . ($i * 5) . "\"/>"
        . "</g>\n";
    $uses .= "      <use href=\"#rg$i\"/>\n";
    // a faint charge travelling round every ring
    $len = 2 * M_PI * $r; $dur = 3.2 + ($i % 4) * 0.6; $dir = $i % 2 ? '-' : '';
    $glints .= "      <circle cx=\"$cx\" cy=\"$cy\" r=\"$r\" fill=\"none\" stroke=\"#bff9ff\" stroke-opacity=\".55\" stroke-width=\"2.2\" stroke-linecap=\"round\" stroke-dasharray=\"16 " . $f($len - 16) . "\">"
        . "<animate attributeName=\"stroke-dashoffset\" from=\"0\" to=\"$dir" . $f($len) . "\" dur=\"{$dur}s\" repeatCount=\"indefinite\"/></circle>\n";
}

$svg = <<<SVG
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" width="512" height="512" role="img" aria-label="Hastra Labs emblem: ten engraved rings linked around an open palm">
  <!-- Hastra Labs · Ten Rings emblem (generated by tools/generate_rings_logo.php; edit that, not this file).
       Ten engraved gunmetal rings linked in a circle: every ring passes over
       one neighbour and under the other (the two woven crossings are re-drawn
       through small clip circles). The formation turns slowly, a faint charge
       travels round each ring, and the core star in the open palm pulses.
       Metal and cyan only: no violet. -->
  <defs>
    <linearGradient id="metal" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0" stop-color="#c3cdd8"/><stop offset=".28" stop-color="#7d8a99"/>
      <stop offset=".6" stop-color="#3a4552"/><stop offset="1" stop-color="#151a21"/>
    </linearGradient>
    <linearGradient id="palm" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0" stop-color="#9ff7ff" stop-opacity=".95"/><stop offset=".55" stop-color="#3a86ff" stop-opacity=".9"/><stop offset="1" stop-color="#0b1f4d" stop-opacity=".95"/>
    </linearGradient>
    <radialGradient id="core" cx=".5" cy=".5" r=".5">
      <stop offset="0" stop-color="#ffffff"/><stop offset=".3" stop-color="#bff9ff" stop-opacity=".8"/><stop offset="1" stop-color="#00f2fe" stop-opacity="0"/>
    </radialGradient>
    <filter id="soft" x="-50%" y="-50%" width="200%" height="200%"><feGaussianBlur stdDeviation="3"/></filter>
$clips$rings  </defs>

  <rect width="512" height="512" rx="72" fill="#04060d"/>

  <!-- the open palm and its core, inside the ring of rings -->
  <g transform="translate(256 262) scale(.34) translate(-256 -290)">
    <path d="M230 460C225 380 215 320 226 270C238 220 274 220 286 270C297 320 287 380 282 460Z" fill="url(#palm)"/>
    <path d="M226 295C195 290 180 270 188 250C196 230 220 255 234 275Z" fill="#4cc9f0"/>
    <path d="M282 285C310 280 330 260 324 242C318 224 295 245 278 265Z" fill="#3a86ff"/>
    <path d="M234 245C228 175 236 145 244 145C252 145 254 175 250 245Z" fill="#7ee8fa"/>
    <path d="M250 230C248 150 254 120 260 120C266 120 268 150 264 230Z" fill="#bff9ff"/>
    <path d="M264 245C262 170 268 140 274 140C280 140 282 170 278 245Z" fill="#3a86ff"/>
  </g>
  <circle cx="256" cy="256" r="30" fill="url(#core)">
    <animate attributeName="r" values="22;34;22" dur="2.6s" repeatCount="indefinite"/>
    <animate attributeName="opacity" values=".55;1;.55" dur="2.6s" repeatCount="indefinite"/>
  </circle>
  <path d="M256 238Q256 256 274 256Q256 256 256 274Q256 256 238 256Q256 256 256 238Z" fill="#fff"/>

  <!-- the ten rings, turning -->
  <g>
    <animateTransform attributeName="transform" type="rotate" from="0 256 256" to="360 256 256" dur="120s" repeatCount="indefinite"/>
$uses$weave    <g filter="url(#soft)" opacity=".7">
$glints    </g>
  </g>
</svg>

SVG;
file_put_contents(__DIR__ . '/../assets/images/hastra-rings-logo.svg', $svg);
echo strlen($svg), " bytes\n";
